# Generated by Django 2.0.6 on 2018-06-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_auto_20180630_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='regdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
