# Generated by Django 2.0.6 on 2018-07-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20180704_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='hit',
            field=models.IntegerField(default=1),
        ),
    ]
