# Generated by Django 2.0.6 on 2018-07-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20180704_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='regdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
